Module feature inspired by Geb
EPadronU/balin pull request #1
Opened 2017-04-11 21:24 UTC by nielsfalk

2017-04-30 15:06 UTC, EPadronU requested changes
This is an awesome work. I really liked what you did and I 'm very thankful for your interest in Balin.

Just a tiny general observation: Try to stick to the two-spaces indentation. I know is quite odd for the Java world but even so, it is the recommended amount in the Google Java Style Guide and is the one I used. Sticking to such style of indentation will avoid a great amount of differences in the BrowserSpek.kt file that are not real code changes. Additionally, it will make the indentation among the project consistent.

2017-04-30 15:06 UTC, EPadronU commented on src/test/kotlin/com/github/epadronu/balin/core/PageSpec.kt
> +
This kind of empty lines should not exist. I know Intellij IDEA introduces them but they should be removed.

2017-04-30 15:06 UTC, EPadronU commented on build.gradle
> +  testCompile "org.jetbrains.kotlin:kotlin-test:1.1.1"
Please introduce inside the ext block the version number for kotlin-test.

2017-04-30 15:06 UTC, EPadronU commented on build.gradle
> +  testCompile 'junit:junit:4.12'
Please introduce inside the ext block the version number for junit.

2017-04-30 15:06 UTC, EPadronU commented on src/test/kotlin/com/github/epadronu/balin/core/BrowserSpec.kt
Like mentioned elsewhere, this kind of empty lines should be removed.

2017-04-30 15:06 UTC, EPadronU commented on src/test/kotlin/com/github/epadronu/balin/core/BrowserSpec.kt
>  /* ***************************************************************************/
Use this separators in the files you created. I know it is a personal taste but it makes the different sections of a Kotlin file more explicit and clear.

2017-04-30 15:06 UTC, EPadronU commented on src/main/kotlin/com/github/epadronu/balin/core/Module.kt
> +    return factory(this.first())
What happens if the list is empty? I could be wrong but shouldn't an exception will be thrown? I don't know if that's the best we can do on such situation.

2017-05-03 21:53 UTC, nielsfalk commented
I'm glad you liked my changes.
I'm ok with any codeformat, as long I can use a Codeformatter. I press cmd+alt+l all the time ;) Can you add the formatter-settings to this repo?

2017-05-03 22:24 UTC, EPadronU commented
At the moment, I don't have anything fancy but a two-spaces indentation. Maybe when I have the time to continue with the development I'll adopt the one from https://github.com/google/styleguide.

2017-05-26 18:48 UTC, dnguyenminh commented
Hi @nielsfalk, 
I got your code, the code was compiled successfully but the tests were not run. How need I do to force the test to run ?

Hi @EPadronU,
I got your code, I ran the the tests and I found some small issues:
- Kotlin index page are updated so your test is out of date, I fixed the validation.
- The browser test about javascript support failed because the core of http unit initialize.

Thank for your code, your idea is clean so I like your ii very much.

2017-05-26 21:18 UTC, EPadronU commented
Hi @dnguyenminh. I took some time to update the dependencies and the tests. Try again with the new changes.

2018-05-05 22:55 UTC, EPadronU commented
The code base has changed a lot since this pull request and a similar feature has been provided.

2018-05-05 22:55 UTC, closed without merging